Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  config.vm.hostname = "aiops-crawler"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end
